// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/redirection.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOriginURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginURLRequest) Reset() {
	*x = GetOriginURLRequest{}
	mi := &file_proto_redirection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginURLRequest) ProtoMessage() {}

func (x *GetOriginURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginURLRequest.ProtoReflect.Descriptor instead.
func (*GetOriginURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_redirection_proto_rawDescGZIP(), []int{0}
}

func (x *GetOriginURLRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *GetOriginURLRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *GetOriginURLRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetOriginURLRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetOriginURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginUrl     string                 `protobuf:"bytes,1,opt,name=origin_url,json=originUrl,proto3" json:"origin_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginURLResponse) Reset() {
	*x = GetOriginURLResponse{}
	mi := &file_proto_redirection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginURLResponse) ProtoMessage() {}

func (x *GetOriginURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginURLResponse.ProtoReflect.Descriptor instead.
func (*GetOriginURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_redirection_proto_rawDescGZIP(), []int{1}
}

func (x *GetOriginURLResponse) GetOriginUrl() string {
	if x != nil {
		return x.OriginUrl
	}
	return ""
}

type GetAccessLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessLogRequest) Reset() {
	*x = GetAccessLogRequest{}
	mi := &file_proto_redirection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessLogRequest) ProtoMessage() {}

func (x *GetAccessLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessLogRequest.ProtoReflect.Descriptor instead.
func (*GetAccessLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_redirection_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccessLogRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type AccessLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortUrlId    int64                  `protobuf:"varint,2,opt,name=short_url_id,json=shortUrlId,proto3" json:"short_url_id,omitempty"`
	AccessTime    string                 `protobuf:"bytes,3,opt,name=access_time,json=accessTime,proto3" json:"access_time,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLog) Reset() {
	*x = AccessLog{}
	mi := &file_proto_redirection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLog) ProtoMessage() {}

func (x *AccessLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLog.ProtoReflect.Descriptor instead.
func (*AccessLog) Descriptor() ([]byte, []int) {
	return file_proto_redirection_proto_rawDescGZIP(), []int{3}
}

func (x *AccessLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccessLog) GetShortUrlId() int64 {
	if x != nil {
		return x.ShortUrlId
	}
	return 0
}

func (x *AccessLog) GetAccessTime() string {
	if x != nil {
		return x.AccessTime
	}
	return ""
}

func (x *AccessLog) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AccessLog) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AccessLog) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetAccessLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AccessLog           `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessLogResponse) Reset() {
	*x = GetAccessLogResponse{}
	mi := &file_proto_redirection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessLogResponse) ProtoMessage() {}

func (x *GetAccessLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessLogResponse.ProtoReflect.Descriptor instead.
func (*GetAccessLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_redirection_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccessLogResponse) GetLogs() []*AccessLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_proto_redirection_proto protoreflect.FileDescriptor

const file_proto_redirection_proto_rawDesc = "" +
	"\n" +
	"\x17proto/redirection.proto\x12\vredirection\"\x83\x01\n" +
	"\x13GetOriginURLRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\"5\n" +
	"\x14GetOriginURLResponse\x12\x1d\n" +
	"\n" +
	"origin_url\x18\x01 \x01(\tR\toriginUrl\"4\n" +
	"\x13GetAccessLogRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"\xad\x01\n" +
	"\tAccessLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\fshort_url_id\x18\x02 \x01(\x03R\n" +
	"shortUrlId\x12\x1f\n" +
	"\vaccess_time\x18\x03 \x01(\tR\n" +
	"accessTime\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\"B\n" +
	"\x14GetAccessLogResponse\x12*\n" +
	"\x04logs\x18\x01 \x03(\v2\x16.redirection.AccessLogR\x04logs2\xc2\x01\n" +
	"\x12RedirectionService\x12U\n" +
	"\fGetOriginURL\x12 .redirection.GetOriginURLRequest\x1a!.redirection.GetOriginURLResponse\"\x00\x12U\n" +
	"\fGetAccessLog\x12 .redirection.GetAccessLogRequest\x1a!.redirection.GetAccessLogResponse\"\x00B\x1bZ\x19redirection-service/protob\x06proto3"

var (
	file_proto_redirection_proto_rawDescOnce sync.Once
	file_proto_redirection_proto_rawDescData []byte
)

func file_proto_redirection_proto_rawDescGZIP() []byte {
	file_proto_redirection_proto_rawDescOnce.Do(func() {
		file_proto_redirection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_redirection_proto_rawDesc), len(file_proto_redirection_proto_rawDesc)))
	})
	return file_proto_redirection_proto_rawDescData
}

var file_proto_redirection_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_redirection_proto_goTypes = []any{
	(*GetOriginURLRequest)(nil),  // 0: redirection.GetOriginURLRequest
	(*GetOriginURLResponse)(nil), // 1: redirection.GetOriginURLResponse
	(*GetAccessLogRequest)(nil),  // 2: redirection.GetAccessLogRequest
	(*AccessLog)(nil),            // 3: redirection.AccessLog
	(*GetAccessLogResponse)(nil), // 4: redirection.GetAccessLogResponse
}
var file_proto_redirection_proto_depIdxs = []int32{
	3, // 0: redirection.GetAccessLogResponse.logs:type_name -> redirection.AccessLog
	0, // 1: redirection.RedirectionService.GetOriginURL:input_type -> redirection.GetOriginURLRequest
	2, // 2: redirection.RedirectionService.GetAccessLog:input_type -> redirection.GetAccessLogRequest
	1, // 3: redirection.RedirectionService.GetOriginURL:output_type -> redirection.GetOriginURLResponse
	4, // 4: redirection.RedirectionService.GetAccessLog:output_type -> redirection.GetAccessLogResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_redirection_proto_init() }
func file_proto_redirection_proto_init() {
	if File_proto_redirection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_redirection_proto_rawDesc), len(file_proto_redirection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_redirection_proto_goTypes,
		DependencyIndexes: file_proto_redirection_proto_depIdxs,
		MessageInfos:      file_proto_redirection_proto_msgTypes,
	}.Build()
	File_proto_redirection_proto = out.File
	file_proto_redirection_proto_goTypes = nil
	file_proto_redirection_proto_depIdxs = nil
}
